# Generated by Django 5.0 on 2024-01-22 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_alter_language_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveSmallIntegerField()),
                ('question_text', models.CharField(max_length=1000)),
                ('question_description', models.TextField()),
                ('starter_code', models.TextField()),
                ('expected_time', models.TimeField()),
                ('expected_output1', models.CharField(max_length=1000)),
                ('expected_output2', models.CharField(max_length=1000)),
                ('expected_output3', models.CharField(max_length=1000)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_question', to='home.language')),
            ],
        ),
    ]
