# Generated by Django 5.0 on 2024-01-14 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d762b968-ed65-43ab-92b2-06e49cd27f14'), editable=False, primary_key=True, serialize=False),
        ),
    ]
