# Generated by Django 5.0 on 2024-01-22 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d790f2e4-a862-49ea-a950-7df9b07886fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
